### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by dvc94ch** [dvc94ch/hashgraph#1]
### complete state machine (m0)
- [ ] rethink api
- [ ] genesis randomness
- [ ] checkpoints use bls-signatures
- [ ] complete author and checkpoint state machine

### harden voter (m1)
- [ ] create a fuzzer
- [ ] add a benchmark
- [ ] add a libp2p example
- [ ] release 0.1.0
